# Generated by Django 5.0.1 on 2024-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_customer_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poi_image",
                    models.ImageField(blank=True, null=True, upload_to="kyc/poi/"),
                ),
                (
                    "poa_image",
                    models.ImageField(blank=True, null=True, upload_to="Kyc/poa/"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"get_latest_by": "pk"},
        ),
    ]
