# Generated by Django 5.0.1 on 2024-01-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_kyc_alter_account_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="poa_image",
            field=models.ImageField(upload_to="Kyc/poa/"),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="poi_image",
            field=models.ImageField(upload_to="kyc/poi/"),
        ),
    ]
