# Generated by Django 5.0.1 on 2024-02-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_position_alter_account_balance_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(db_index=True, default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="rank",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.rank"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.position",
            ),
        ),
    ]
