# Generated by Django 5.0.1 on 2024-02-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_staff_phone_alter_customer_rank_alter_staff_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
