name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for linting
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flake8
        run: |
          python -m pip install flake8

      - name: Lint code
        run: flake8 .

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for testing
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: docker-compose up -d

