name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install additional tools
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          pip install autopep8 isort black djlint pip-audit yamllint

      - name: Auto-format code
        run: |
          autopep8 --in-place --aggressive --aggressive -r .
          isort . --profile black
          black .

      - name: Run static analysis
        run: |
          djlint .
          pip-audit
          yamllint *.yml
          shellcheck *.sh

  deployment:
    runs-on: ubuntu-latest
    needs: [static]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: docker-compose up -d

