name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for linting
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylama djlint pip-audit yamllint

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Lint Python code with pylama
        run: pylama .

      - name: Lint Django templates with djlint
        run: djlint .

      - name: Audit Python packages with pip-audit
        run: pip-audit

      - name: Lint YAML files with yamllint
        run: yamllint *.yml

      - name: Lint shell scripts with ShellCheck
        run: shellcheck *.sh

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for testing
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20 for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: docker-compose up -d

